language: java

install:
  - docker --version
  - docker-compose --version

services:
  - docker

script:
  - docker build --rm -f Dockerfile -t rashpile/spring-hello:latest .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master